name: swift_control
description: "SwiftControl - Control your virtual riding"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.0.0
  universal_ble: any
  protobuf: ^3.1.0
  permission_handler: ^11.4.0
  dartx: any
  image_picker: ^1.1.2
  pointycastle: any
  keypress_simulator: ^0.2.0
  shared_preferences: ^2.5.3
  flex_color_scheme: ^8.2.0
  accessibility:
    path: accessibility

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
